version: '3.3'

services:
  postgres:
    image: postgres
    volumes:
      - ezybucks_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ezybucks
    ports:
      - "5432:5432"

  backend:
    image: ezybucks/backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - "postgres"
    restart: always
    environment:
      NODE_ENV: production

  frontend:
    image: ezybucks/frontend:latest
    ports: 
      - "3001:3000"
    depends_on: 
      - backend
    restart: always

volumes:
  ezybucks_data:
